"use client";

import { useRef, useState } from "react";
import { ArrowRight, Bath, CheckCircle2, ChevronLeft, ChevronRight, MapPin, Minus, Phone, Plus, ShieldCheck, Siren, Star } from "lucide-react";
import { BUSINESS, FAQS, GALLERY, REVIEWS, SERVICES, STEPS, WHY, IMG } from "./data";
import { Label, Reveal, SafeImage } from "./shared";

export function PromiseSection() {
  return <section className="bg-white px-5 py-24 md:px-8 md:py-32"><div className="mx-auto max-w-5xl"><Reveal><div className="grid gap-6 md:grid-cols-[auto_1fr] md:gap-10"><Label>Our promise</Label><p className="text-2xl font-light leading-snug tracking-tight text-slate-800 md:text-4xl md:leading-[1.25]">Your home runs on water. We protect it with skilled, licensed plumbers, honest pricing and repairs that last, so you can stop worrying about what's behind the walls.</p></div></Reveal></div></section>;
}

export function ServicesSection() {
  return <section id="services" className="scroll-mt-20 bg-slate-50 px-5 py-24 md:px-8"><div className="mx-auto max-w-7xl"><Reveal><Label>What we do</Label><h2 className="mt-5 max-w-2xl text-4xl font-light tracking-tight text-slate-900 md:text-5xl">Every plumbing problem, one call away.</h2></Reveal><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{SERVICES.map((service, index) => <Reveal key={service.title} delay={index * 80}><div className="group h-full rounded-lg border border-slate-200 bg-white p-7 transition duration-300 hover:-translate-y-1 hover:border-sky-300 hover:shadow-xl hover:shadow-sky-100"><span className="flex h-12 w-12 items-center justify-center rounded-lg bg-sky-100 text-[#0d4a86] transition group-hover:bg-[#0d4a86] group-hover:text-white"><service.icon className="h-6 w-6" /></span><h3 className="mt-6 text-xl font-medium text-slate-900">{service.title}</h3><p className="mt-2 leading-relaxed text-slate-600">{service.text}</p></div></Reveal>)}</div></div></section>;
}

export function StatsSection() {
  const stats = [{ value: "24/7", label: "Emergency response" }, { value: "100%", label: "Upfront quotes" }, { value: "Same-day", label: "Service available" }, { value: "5★", label: "Customer care" }];
  return <section className="bg-[#0a2f57] px-5 py-16 text-white md:px-8"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-10 md:grid-cols-4">{stats.map((stat, index) => <Reveal key={stat.label} delay={index * 100}><div className="border-l border-white/20 pl-5"><p className="text-4xl font-light md:text-5xl">{stat.value}</p><p className="mt-2 text-sm uppercase tracking-wider text-white/60">{stat.label}</p></div></Reveal>)}</div></section>;
}

export function WhyUsSection() {
  return <section id="why-us" className="scroll-mt-20 bg-white px-5 py-24 md:px-8 md:py-32"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-2"><Reveal><div className="relative"><SafeImage src={IMG.crew} alt="Plumber at work" className="h-[460px] w-full rounded-lg object-cover md:h-[560px]" /><div className="absolute -bottom-6 right-4 max-w-[260px] rounded-lg bg-[#0d4a86] p-5 text-white shadow-2xl md:-right-6"><div className="flex gap-1 text-amber-300">{Array.from({ length: 5 }, (_, index) => <Star key={index} className="h-4 w-4 fill-current" />)}</div><p className="mt-2 text-sm leading-snug">Neighbors trust us to treat their homes like our own.</p></div></div></Reveal><div><Reveal><Label>Why choose us</Label><h2 className="mt-5 text-4xl font-light tracking-tight text-slate-900 md:text-5xl">The plumbers Atlanta calls twice.</h2><p className="mt-5 max-w-lg text-lg leading-relaxed text-slate-600">We built A A Buckley Plumbing on a simple idea: show up, tell the truth, do excellent work.</p></Reveal><div className="mt-10 grid gap-7 sm:grid-cols-2">{WHY.map((reason, index) => <Reveal key={reason.title} delay={index * 100}><reason.icon className="h-7 w-7 text-[#0d4a86]" /><h3 className="mt-3 text-lg font-medium text-slate-900">{reason.title}</h3><p className="mt-1 text-slate-600">{reason.text}</p></Reveal>)}</div></div></div></section>;
}

export function ProcessSection() {
  return <section id="process" className="scroll-mt-20 bg-slate-50 px-5 py-24 md:px-8"><div className="mx-auto max-w-7xl"><Reveal><Label>How it works</Label><h2 className="mt-5 text-4xl font-light tracking-tight text-slate-900 md:text-5xl">Simple from start to finish.</h2></Reveal><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{STEPS.map((step, index) => <Reveal key={step.title} delay={index * 100}><div className="relative h-full rounded-lg bg-white p-7 shadow-sm"><span className="absolute right-6 top-5 text-5xl font-light text-slate-100">0{index + 1}</span><step.icon className="h-8 w-8 text-[#0d4a86]" /><h3 className="mt-5 text-xl font-medium text-slate-900">{step.title}</h3><p className="mt-2 text-slate-600">{step.text}</p></div></Reveal>)}</div></div></section>;
}

export function GallerySection() {
  const rail = useRef<HTMLDivElement>(null);
  const scroll = (direction: number) => rail.current?.scrollBy({ left: direction * 440, behavior: "smooth" });
  return <section id="work" className="scroll-mt-20 overflow-hidden bg-white py-24 md:py-32"><div className="mx-auto flex max-w-7xl items-end justify-between gap-6 px-5 md:px-8"><Reveal><Label>Past work</Label><h2 className="mt-5 max-w-xl text-4xl font-light tracking-tight text-slate-900 md:text-5xl">Craftsmanship you can see.</h2></Reveal><div className="hidden gap-2 md:flex"><button aria-label="Scroll gallery left" onClick={() => scroll(-1)} className="flex h-11 w-11 items-center justify-center rounded-md border border-slate-300 text-slate-700 hover:bg-slate-100"><ChevronLeft className="h-5 w-5" /></button><button aria-label="Scroll gallery right" onClick={() => scroll(1)} className="flex h-11 w-11 items-center justify-center rounded-md bg-[#0d4a86] text-white hover:bg-[#0a3a6e]"><ChevronRight className="h-5 w-5" /></button></div></div><div ref={rail} className="mt-12 flex snap-x snap-mandatory gap-5 overflow-x-auto scroll-smooth px-5 pb-4 md:px-8 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{GALLERY.map((item) => <figure key={item.title} className="group relative h-[420px] w-[280px] shrink-0 snap-start overflow-hidden rounded-lg sm:w-[340px] md:h-[480px] md:w-[400px]"><SafeImage src={item.img} alt={item.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#0a2f57]/85 via-transparent to-transparent opacity-80" /><figcaption className="absolute inset-x-0 bottom-0 p-5 text-white"><span className="rounded-full bg-white/20 px-3 py-1 text-[11px] uppercase tracking-wider backdrop-blur">{item.tag}</span><p className="mt-3 text-xl">{item.title}</p></figcaption></figure>)}</div></section>;
}

export function ReviewsSection() {
  return <section id="reviews" className="scroll-mt-20 bg-[#0a2f57] px-5 py-24 text-white md:px-8"><div className="mx-auto max-w-7xl"><Reveal><Label dark>Customer stories</Label><h2 className="mt-5 max-w-2xl text-4xl font-light tracking-tight md:text-5xl">Homeowners who stopped worrying about leaks.</h2></Reveal><div className="mt-14 grid gap-5 md:grid-cols-3">{REVIEWS.map((review, index) => <Reveal key={review.name} delay={index * 120}><article className="h-full rounded-lg border border-white/15 bg-white/5 p-7 backdrop-blur"><div className="flex gap-1 text-amber-300">{Array.from({ length: 5 }, (_, starIndex) => <Star key={starIndex} className="h-4 w-4 fill-current" />)}</div><p className="mt-4 leading-relaxed text-white/90">&ldquo;{review.text}&rdquo;</p><p className="mt-6 font-medium">{review.name}</p><p className="text-sm text-white/55">{review.area}</p></article></Reveal>)}</div></div></section>;
}

export function EmergencyCTA() {
  return <section className="bg-gradient-to-r from-[#0d4a86] to-[#1c78c8] px-5 py-16 text-white md:px-8"><Reveal><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="flex items-center gap-2 text-sm uppercase tracking-widest text-white/80"><Siren className="h-4 w-4" />Plumbing emergency?</p><h2 className="mt-3 text-3xl font-light md:text-5xl">Don't wait. Water damage spreads fast.</h2></div><a href={`tel:${BUSINESS.tel}`} className="flex items-center gap-3 rounded-md bg-white px-8 py-4 text-lg font-semibold text-[#0a2f57] shadow-xl transition hover:scale-[1.03]"><Phone className="h-5 w-5" />{BUSINESS.phone}</a></div></Reveal></section>;
}

export function FAQSection() {
  const [open, setOpen] = useState<number | null>(0);
  return <section id="faq" className="scroll-mt-20 bg-white px-5 py-24 md:px-8 md:py-32"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[1fr_1.6fr]"><Reveal><Label>FAQ</Label><h2 className="mt-5 text-4xl font-light tracking-tight text-slate-900 md:text-5xl">Questions, answered.</h2><p className="mt-4 text-slate-600">Can't find what you need? Give us a call, we're happy to help.</p><a href={`tel:${BUSINESS.tel}`} className="mt-6 inline-flex items-center gap-2 font-medium text-[#0d4a86] hover:underline"><Phone className="h-4 w-4" />{BUSINESS.phone}</a></Reveal><div className="divide-y divide-slate-200 border-y border-slate-200">{FAQS.map((faq, index) => { const isOpen = open === index; return <div key={faq.q}><button onClick={() => setOpen(isOpen ? null : index)} aria-expanded={isOpen} className="flex w-full items-center justify-between gap-6 py-6 text-left"><span className="text-lg font-medium text-slate-900">{faq.q}</span><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-sky-100 text-[#0d4a86]">{isOpen ? <Minus className="h-4 w-4" /> : <Plus className="h-4 w-4" />}</span></button><div className={`grid transition-all duration-300 ${isOpen ? "grid-rows-[1fr] pb-6" : "grid-rows-[0fr]"}`}><p className="overflow-hidden leading-relaxed text-slate-600">{faq.a}</p></div></div>; })}</div></div></section>;
}

export function ContactSection() {
  const [sent, setSent] = useState(false);
  const input = "w-full rounded-md border border-slate-300 bg-white px-4 py-3 text-slate-900 outline-none transition focus:border-[#0d4a86] focus:ring-2 focus:ring-sky-200";

  return <section id="contact" className="scroll-mt-20 bg-slate-50 px-5 py-24 md:px-8"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-2"><Reveal><Label>Get in touch</Label><h2 className="mt-5 text-4xl font-light tracking-tight text-slate-900 md:text-5xl">Get your free quote today.</h2><p className="mt-4 max-w-md text-lg text-slate-600">Tell us what's going on and we'll get back to you quickly with a clear plan and honest price.</p><ul className="mt-8 space-y-5 text-slate-700"><li className="flex items-start gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-lg bg-white text-[#0d4a86] shadow-sm"><Phone className="h-5 w-5" /></span><a href={`tel:${BUSINESS.tel}`} className="pt-2 font-medium hover:text-[#0d4a86]">{BUSINESS.phone}</a></li><li className="flex items-start gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-lg bg-white text-[#0d4a86] shadow-sm"><MapPin className="h-5 w-5" /></span><span className="pt-2">{BUSINESS.address}</span></li></ul></Reveal><Reveal delay={150}>{sent ? <div className="flex h-full min-h-[360px] flex-col items-center justify-center rounded-lg bg-white p-10 text-center shadow-lg"><CheckCircle2 className="h-14 w-14 text-emerald-500" /><h3 className="mt-4 text-2xl font-medium text-slate-900">Request received!</h3><p className="mt-2 text-slate-600">We'll be in touch shortly. For urgent issues, call {BUSINESS.phone}.</p></div> : <form onSubmit={(event) => { event.preventDefault(); setSent(true); }} className="space-y-4 rounded-lg bg-white p-7 shadow-lg md:p-9"><div className="grid gap-4 sm:grid-cols-2"><input required name="name" autoComplete="name" placeholder="Full name" className={input} /><input required name="phone" type="tel" autoComplete="tel" placeholder="Phone number" className={input} /></div><select required name="service" defaultValue="" className={input}><option value="" disabled>What do you need help with?</option>{SERVICES.map((service) => <option key={service.title}>{service.title}</option>)}</select><textarea name="details" rows={4} placeholder="Describe the problem" className={input} /><button type="submit" className="flex w-full items-center justify-center gap-2 rounded-md bg-[#0d4a86] py-3.5 font-semibold text-white transition hover:bg-[#0a3a6e]">Request my free quote<ArrowRight className="h-4 w-4" /></button></form>}</Reveal></div></section>;
}